/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dzymgpwxzkrlrpqqnyna"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6eW1ncHd4emtybHJwcXFueW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczNjI4MDgsImV4cCI6MjA5MjkzODgwOH0.BKd9-b2derkmBCM9qzEI_HkeJGTRPiUgBMp28xZIlQ4"
